### ISSUE TITLE
When cortical properties window is open, clicking on different cortical areas should update its context

### ISSUE THREAD

**Issue by m-nadji-tehrani** [feagi/brain-visualizer#251] opened 2024-06-15 15:20 UTC
We had it in past where when a cortical area on whether CB or BM was clicked the cortical properties data where updated within the cortical properties window when open. Need to bring it back.

**Comment by Amir-Rasteg** [comment] 2024-06-17 14:53
duplicate of https://github.com/feagi/brain-visualizer/issues/235

**Closed by Amir-Rasteg** 2024-06-17 14:53 UTC
