### ISSUE TITLE
memory region causes crash

### ISSUE THREAD

**Issue by jenz512** [feagi/brain-visualizer#268] opened 2024-06-27 21:54 UTC
dropping the memory region into the essential genome causes it to crash
<img width="1141" alt="Screenshot 2024-06-27 at 5 53 50 PM" src="https://github.com/feagi/brain-visualizer/assets/143905253/435fb016-10a7-4295-aece-bbeb94cf5c46">

**Comment by Amir-Rasteg** [comment] 2024-07-01 15:50
@jenz512 I need more information as to how to reproduce this issue. I tried creating memory cortical areas, mapping them in and out of regions and couldnt reproduce this.
@m-nadji-tehrani I have a hunch this is a feagi issue since the error in the screenshot is pointing out that data being returned isnt containing what is expected, but I need to be able to repo this to confirm

**Comment by Amir-Rasteg** [comment] 2024-07-09 14:57
closing this issue in favor of issue https://github.com/feagi/brain-visualizer/issues/274 where bv has a failsafe for this issue, but the issue needs to be fixed proper feagi side

**Closed by Amir-Rasteg** 2024-07-09 14:57 UTC
