### ISSUE TITLE
Every time when the cortical in CB is moved, menu popped without double click

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#295] opened 2024-07-22 13:30 UTC
https://github.com/user-attachments/assets/ff9557f6-b1ab-4791-b707-481e04c7de96

**Comment by Amir-Rasteg** [comment] 2024-07-22 20:59
duplicate of  https://github.com/feagi/brain-visualizer/issues/283

**Closed by Amir-Rasteg** 2024-07-22 20:59 UTC
