### ISSUE TITLE
BV crash when you edit properties

### ISSUE THREAD

**Issue by Kakcalu13** [feagi/brain-visualizer#367] opened 2024-09-29 17:52 UTC
![image](https://github.com/user-attachments/assets/885b5b9a-d3a0-4a46-a968-1b626bb33519)

steps:
1) Click central to open the leftbar
2) update firing threshold

**Comment by Amir-Rasteg** [comment] 2024-09-30 14:55
duplicate of https://github.com/feagi/brain-visualizer/issues/368

**Closed** 2024-09-30 18:19 UTC
